export const pfp: string[] = [
    "Gobo [1]",
    "Terra [2]",
    "Unknown [3]",
    "Unknown [4]",
    "Scratch Cat :skull: [5]",
    "Unknown [6]",
    "Unknown [7]",
    "Unknown [8]",
    "Unknown [9]",
    "Unknown [10]",
    "Unknown [11]",
    "Unknown [12]",
    "Unknown [13]",
    "Unknown [14]",
    "Unknown [15]",
    "Unknown [16]",
    "Clown Meowy [17]",
    "Unknown [18]",
    "Unknown [19]",
    "Unknown [20]",
    "Unknown [21]",
    "Meowy [22]",
    "@DaCatBlock [23]",
    "a lawnmower [24]",
    "a duck [25]",
    "a rubber duck [26]",
    "the Meower Media logo [27]",
    "Grandpa Meowy [28]",
    "BetterMeowy [29]",
    "Purple Meowy [30]",
    "Red Meowy [31]",
    "Blue Meowy [32]",
    "Tux [33]",
    "a dango [34]",
    "Unknown [35]",
    "Unknown [36]",
    "Unknown [37]",
    "Unknown [38]",
    "Unknown [39]",
];

export const lvl: string[] = [
    "User [0]",
    "Low-level Moderator [1]",
    "Moderator [2]",
    "Administratior [3]",
    "Sysadmin [4]"
];