export const pfp: string[] = [
    "Gobo",
    "Terra",
    "Unknown",
    "Unknown",
    "Scratch Cat :skull:",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Clown Meowy",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Meowy",
    "a Cat block",
    "a lawnmower",
    "a duck",
    "a rubber duck",
    "the Meower Media logo",
    "Grandpa Meowy",
    "BetterMeowy",
    "Purple Meowy",
    "Red Meowy",
    "Blue Meowy",
    "Tux",
    "a dango",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
    "Unknown",
];

export const lvl: string[] = [
    "Low-level Moderator",
    "Moderator",
    "Administratior",
    "Either Mike, Tnix, or MeowyMod"
];